# Breast Cancer

# Imports

In [15]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [16]:
cancer = load_breast_cancer()

In [17]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [18]:
df = pd.DataFrame(cancer.data,columns=cancer.feature_names)
target = cancer.target

In [19]:
df.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

## Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X = df
y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

## Support Vectors machine

In [25]:
from sklearn.svm import SVC

In [30]:
model = SVC()

In [31]:
model.fit(X_train, y_train)

SVC()

In [32]:
prediction = model.predict(X_test)

Evaluation

In [33]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
print(confusion_matrix(y_test,prediction),'\n')
print(classification_report(y_test,prediction),'\n')

[[ 61  13]
 [  1 113]] 

              precision    recall  f1-score   support

           0       0.98      0.82      0.90        74
           1       0.90      0.99      0.94       114

    accuracy                           0.93       188
   macro avg       0.94      0.91      0.92       188
weighted avg       0.93      0.93      0.92       188
 



### After Using Grid Search

In [36]:
from sklearn.model_selection import GridSearchCV

In [50]:
parameters = {'C':[0.1,1,10,100,1000],'gamma':[10,1,0.1,0.01,0.001,0.0001,0.00001],'kernel':['rbf']}

In [51]:
grid = GridSearchCV(SVC(),parameters,verbose=3,refit=True)

In [52]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 35 candidates, totalling 175 fits
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.636, total=   0.1s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s


[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.645, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.645, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.636, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.632, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.632, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.645, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .

[CV] .......... C=10, gamma=10, kernel=rbf, score=0.636, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.645, total=   0.0s
[CV] C=10, gamma=10, kernel=rbf ......................................
[CV] .......... C=10, gamma=10, kernel=rbf, score=0.645, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.636, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.632, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] .

[CV] ...... C=100, gamma=1e-05, kernel=rbf, score=0.961, total=   0.0s
[CV] C=100, gamma=1e-05, kernel=rbf ..................................
[CV] ...... C=100, gamma=1e-05, kernel=rbf, score=0.947, total=   0.0s
[CV] C=100, gamma=1e-05, kernel=rbf ..................................
[CV] ...... C=100, gamma=1e-05, kernel=rbf, score=0.974, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.636, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.632, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] ........ C=1000, gamma=10, kernel=rbf, score=0.645, total=   0.0s
[CV] C=1000, gamma=10, kernel=rbf ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 175 out of 175 | elapsed:    2.0s finished


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001, 1e-05],
                         'kernel': ['rbf']},
             verbose=3)

Analysis


In [54]:
grid.best_params_

{'C': 1000, 'gamma': 1e-05, 'kernel': 'rbf'}

In [55]:
grid_prediction = grid.predict(X_test)

In [57]:
print(confusion_matrix(y_test,grid_prediction),'\n')
print(classification_report(y_test,grid_prediction),'\n')

[[ 69   5]
 [  4 110]] 

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        74
           1       0.96      0.96      0.96       114

    accuracy                           0.95       188
   macro avg       0.95      0.95      0.95       188
weighted avg       0.95      0.95      0.95       188
 



In [60]:
grid_prediction = grid.predict(X_test)

In [61]:
print(confusion_matrix(y_test,grid_prediction),'\n')
print(classification_report(y_test,grid_prediction),'\n')

[[ 69   5]
 [  4 110]] 

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        74
           1       0.96      0.96      0.96       114

    accuracy                           0.95       188
   macro avg       0.95      0.95      0.95       188
weighted avg       0.95      0.95      0.95       188
 

